### ISSUE TITLE
registration dependent on fixed session id

### ISSUE THREAD

**Issue by twistsmyth** [davidearl/webauthn#1]
if you clear your cookies/$_SESSION after registration you get error "login failed: Bad Request: username not set" while attempting to login.

**Comment by davidearl** [comment]
Thanks for this. The code should have been saving the username in the session after retrieving it in the right hand form submission.

I also now used a different name for the session entry between registration and login to avoid mixing up the two.

**Comment by geraldkrug** [comment]
http://g-d-k.com/authn/example/index.php

I have it working :)
