### ISSUE TITLE
random_bytes with php5.6

### ISSUE THREAD

**Issue by hregis** [davidearl/webauthn#22]
Hello

you use "random_bytes" function, this function is only in php 7+

we should either limit the "compose" with php 7+

OR use this library to make it compatible with php 5.6 
https://github.com/paragonie/random_compat

OR use "openssl_random_pseudo_bytes" compatible with 5.6 and 7+

Thanks

**Comment by davidearl** [comment]
Yes, you're right. I'm tempted to say PHP 7 only as PHP5.6 is no longer supported, but it does still seem to be in widespread use, so I'll look at using openssl for this for older versions. It may be a while before I can get to do this.

**Comment by hregis** [comment]
@davidearl 
i install manually this library with your library and all works with php5.6

https://github.com/paragonie/random_compat

"random_compat" detect if you use php7+ or not
