### ISSUE TITLE
importing the library

### ISSUE THREAD

**Issue by cube-access-repo** [davidearl/webauthn#41]
Confudes regaridn importing the webauthn.php directory to the project.. does that get imported by composer..... i didnt see any require in the index.php file

**Comment by davidearl** [comment]
Umm... it's on line 8 of index.php (the example), pretty much the first line of code!

**Comment by cube-access-repo** [comment]
Hi, weird im using docker and composer and i had to include webauthn.php directly in the file before the vendor... otherwise it wouldnt work.....
2 questions: 1)do u know how i can add an icon to the navigator popup?
Can u give me an example of how to stor multiple keys per user?
