### ISSUE TITLE
Timeout not implemented?

### ISSUE THREAD

**Issue by Skittel** [davidearl/webauthn#45]
Hello,

**Thanks for this great software!**

I'm current reducing the html & js part to a minimum.

My php-skript creates a html output with the challenge allready in a variable.
The js-part only creates the response and calls itself with the response as a get-parameter.

This works fines.
https://rdpdev.secureaccess.pro/testwa/example/4login.php

But I realized that there is no timeout.
I can refresh the page with the get-parameter and after 5 minutes $webauthn->authenticate return "OK".

I see the timeout fields during creation, but they are not checked.

This does not happen in your JS-version and POST.
But this error should be there even if it is harder to show.

Stefan

**Comment by davidearl** [comment]
Thanks for this. Do you think it is the same issue as #40?

**Comment by Skittel** [comment]
Hello David,
Yes, this is correct.
I continue there.
Stefan
