### ISSUE TITLE
`composer require` fails with InvalidArgumentException

### ISSUE THREAD

**Issue by Chaz6** [davidearl/webauthn#53]
I created a blank project with `composer init`. I then tried to run `composer require davidearl/webauthn` but it failed with the following output:-

```
  [InvalidArgumentException]
  Could not find a version of package davidearl/webauthn matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```

How can I add this to my project? When I was prompted for a value for "Minimum Stability" I left it blank, so I presume it uses stable as a default.

**Comment by joszz** [comment]
Did you at all try to Google this!?
This is what you find if you Google this while removing the reference to this package
https://stackoverflow.com/questions/41149552/composer-packagist-could-not-find-package-for-minimum-stability
