### ISSUE TITLE
Safari: registration failed: Bad Request: cannot decode key response (5)

### ISSUE THREAD

**Issue by euroxs** [davidearl/webauthn#55]
User Registration in Safari returns this error. Something goes wrong when checking the rpId hash? 

Both Firefox and Chrome work fine. Also after registering in another browser, User Login does work in Safari.

**Comment by davidearl** [comment]
Presumably you're on a Mac, yes? OS version? what authenticator are you using - built-in fingerprint reader? Yubico key? Face ID?

I think Safari support for webauthn is quite recent. I know it works in iOS 15 and 16 Safari now, but I haven't checked Mac Safari recently.

**Comment by euroxs** [comment]
I am using Safari 16 on macOS Monterey (12.6) with a Yubico key.

**Comment by davidearl** [comment]
OK, I can reproduce it, thanks. However, it appears to be a problem with Safari (I also have 16.0, 17614), as it works ok in the latest Safari Technology Preview 155 (16.4) also on Monterey 12.6. Whilst there may be a work round I could do, it doesn't seem worth it if they have already fixed the problem in the next release.
